name: Validate Main
on:
  push:
    branches:
      - main
  pull_request:

env:
  AZURE_FUNCTIONAPP_NAME: matrixmesh  # set this to your application's name

jobs:
  # tests:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       project: 
  #       - 'MatrixMeshMath.Tests'
  #       - 'MatrixMeshFunctions.Tests'
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-dotnet@v1.7.2
  #     with:
  #       dotnet-version: '6.0.x'
  #   - name: test
  #     run: |
  #       dotnet restore ${{ matrix.project }}
  #       dotnet test ${{ matrix.project }}

  deploy:
    needs: tests
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '6.0.x'
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'build functions'
      run: |
        pushd MatrixMeshFunctions
        dotnet build --configuration Release --output ./output
        popd

    - run: |
        ls './MatrixMeshFunctions/output'
    - name: 'Publish Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './MatrixMeshFunctions/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}