name: Validate Main
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: 
        - 'MatrixMeshMath.Tests'
        - 'MatrixMeshFunctions.Tests'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '6.0.x'
    - run: |
        dotnet restore ${{ matrix.project }}
        dotnet test ${{ matrix.project }}